services:
  mongodb:
    build: ./mongodb
    image: joindevops/mongodb:v1
    container_name: mongodb
  networks:
  default:
    #river: bridge
    name: roboshop
    external: false # true if you have created network manually using docker network command